<?php


namespace app\mobile\controller;


use app\model\FriendshipLink;
use app\BaseController;
use think\facade\Env;
use think\facade\View;

class Base extends BaseController
{
    protected $prefix;
    protected $redis_prefix;
    protected $uid;
    protected $end_point;
    protected $tpl;
    protected $mobile_url;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = session('xwx_user_id');
        $this->prefix = Env::get('database.prefix');
        $this->redis_prefix = Env::get('cache.prefix');
        $this->end_point = config('seo.book_end_point');
        $tpl_root = './template/'.config('site.tpl').'/m/';
        $controller = strtolower($this->request->controller());
        $action = strtolower($this->request->action());
        $this->tpl = $tpl_root.$controller.'/'.$action.'.html';
        $this->mobile_url = config('site.mobile_domain');

        $links = cache('friendshipLink');
        if ($links == false){
            $links = FriendshipLink::select();
            cache('friendshipLink',$links,null,'redis');
        }
        View::assign([
            'url' => config('site.domain'),
            'site_name' => config('site.site_name'),
            'mobile_url' => $this->mobile_url,
            'api_url' => config('site.api_domain'),
            'links' => $links,
            'book_ctrl' => BOOKCTRL,
            'chapter_ctrl' => CHAPTERCTRL,
            'booklist_act' => BOOKLISTACT,
            'search_ctrl' => SEARCHCTRL,
            'rank_ctrl' => RANKCTRL,
            'update_act' => UPDATEACT,
            'author_ctrl' => AUTHORCTRL,
            'end_point' => config('seo.book_end_point'),
            'xwx_user_id' => session('xwx_user_id'),
            'xwx_user' => session('xwx_user'),
            'xwx_nick_name' => session('xwx_nick_name'),
            'xwx_user_mobile'=> session('xwx_user_mobile')
        ]);
    }
}