<?php


namespace app\mobile\controller;


use app\common\RedisHelper;
use app\model\Book;
use app\model\Comments;
use app\model\Tail;
use app\model\UserFavor;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\Db;
use think\facade\View;

class Tails extends Base
{
    protected $tailService;
    protected $bookService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->tailService = app('tailService');
        $this->bookService = app('bookService');
    }

    public function list()
    {
        $data = $this->tailService->getlist(20, $this->end_point, 'id');
//        unset($data['page']['query']['page']);
//        $param = '';
//        foreach ($data['page']['query'] as $k => $v) {
//            $param .= '&' . $k . '=' . $v;
//        }
        View::assign([
            'tails' => $data,
            'total' => count($data),
            'header_title' => '书单推荐'
        ]);
        return view($this->tpl);
    }

    public function index($id)
    {
        $tail = cache('tail:'.$id);
        if ($tail == false) {
            $tail = Tail::where('id', '=', $id)->findOrFail();
            cache('tail' . $id, $tail, null, 'redis');
        }
        $book = cache('book:' . $tail->book_id);
        $tags = cache('tags:book:' . $tail->book_id);
        if ($book == false) {
            try {
                $book = Book::with(['chapters' => function ($query) {
                    $query->order('chapter_order');
                }])->findOrFail($tail->book_id);
                $book['book_name'] = $tail->tailname;
            } catch (DataNotFoundException $e) {
                abort(404, $e->getMessage());
            } catch (ModelNotFoundException $e) {
                abort(404, $e->getMessage());
            }
            $tags = [];
            if (!empty($book->tags)) {
                $tags = explode('|', $book->tags);
            }
            cache('tailBook:' . $tail->book_id, $book, null, 'redis');
            cache('tagsBook:' . $tail->book_id, $tags, null, 'redis');
        }
        $redis = RedisHelper::GetInstance();
        $day = date("Y-m-d", time());
        //以当前日期为键，增加点击数
        $redis->zIncrBy('click:' . $day, 1, $book->id);

        $recommand = cache('randBooks:' . $book->tags);
        if (!$recommand) {
            $recommand = $this->bookService->getRecommand($book->tags, $this->end_point);
            cache('randBooks:' . $book->tags, $recommand, null, 'redis');
        }

        $updates = cache('updateBooks');
        if (!$updates) {
            $updates = $this->bookService->getBooks($this->end_point, 'last_time', [], 20);
            cache('updateBooks', $updates, null, 'redis');
        }

        $start = cache('bookStart:' . $book->id);
        if ($start == false) {
            $db = Db::query('SELECT id FROM ' . $this->prefix . 'chapter WHERE book_id = ' . $book->id . ' ORDER BY id LIMIT 1');
            $start = $db ? $db[0]['id'] : -1;
            cache('bookStart:' . $book->id, $start, null, 'redis');
        }

        $comments = $this->getComments($book->id);

        $isfavor = 0;
        if (!is_null($this->uid)) {
            $where[] = ['user_id', '=', $this->uid];
            $where[] = ['book_id', '=', $book->id];
            try {
                $userfavor = UserFavor::where($where)->findOrFail();
                $isfavor = 1;
            } catch (DataNotFoundException $e) {
            } catch (ModelNotFoundException $e) {
            }
        }

        $start_pay = cache('maxChapterOrder:' . $book->id);
        if (!$start_pay) {
            if ($book->start_pay >= 0) {
                $start_pay = $book->start_pay; //如果是正序，则开始付费章节就是设置的
            } else { //如果是倒序付费设置
                $abs = abs($book->start_pay) - 1; //取得倒序的绝对值，比如-2，则是倒数第2章开始付费
                $max_chapter_order = Db::query("SELECT MAX(chapter_order) as max FROM " . $this->prefix . "chapter WHERE book_id=:id",
                    ['id' => $book->id])[0]['max'];
                cache('maxChapterOrder:' . $book->id, $max_chapter_order);
                $start_pay = (float)$max_chapter_order - $abs; //计算出起始付费章节
            }
        }

        $clicks = cache('bookClicks:' . $book->id);
        if (!$clicks) {
            $clicks = $this->bookService->getClicks($book->id, $this->prefix);
            cache('bookClicks:' . $book->id, $clicks);
        }

        View::assign([
            'book' => $book,
            'tags' => $tags,
            'start' => $start,
            'updates' => $updates,
            'recommand' => $recommand,
            'isfavor' => $isfavor,
            'comments' => $comments,
            'start_pay' => $start_pay,
            'clicks' => $clicks,
            'header_title' => $book->book_name,
        ]);
        return view($this->tpl);
    }

    public function commentadd()
    {
        $book_id = input('book_id');
        $redis = RedisHelper::GetInstance();
        if ($redis->exists('comment_lock:' . $this->uid)) {
            return json(['msg' => '每10秒只能评论一次', 'err' => 1]);
        } else {
            $comment = new Comments();
            $comment->user_id = $this->uid;
            $comment->book_id = $book_id;
            $comment->content = strip_tags(input('comment'));
            $result = $comment->save();
            if ($result) {
                $redis->set('comment_lock:' . $this->uid, 1, 10); //加10秒锁
                cache('comments:' . $book_id, null);
                return json(['msg' => '评论成功', 'err' => 0]);
            } else {
                return json(['msg' => '评论失败', 'err' => 1]);
            }
        }
    }

    private function getComments($book_id)
    {
        $comments = cache('comments:' . $book_id);
        if (!$comments) {
            $comments = Comments::with('user')->where('book_id', '=', $book_id)
                ->order('create_time', 'desc')->limit(0, 5)->select();
            cache('comments:' . $book_id, $comments);
        }
        return $comments;
    }
}