<?php


namespace app\index\controller;

use app\BaseController;
use app\model\FriendshipLink;
use think\App;
use think\facade\Env;
use think\facade\View;

class Base extends BaseController
{
    //protected $middleware = [\app\middleware\Before::class];
    protected $prefix;
    protected $redis_prefix;
    protected $uid;
    protected $end_point;
    protected $tpl;
    protected $links;
    protected $url;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $controller = strtolower($this->request->controller());
        $action = strtolower($this->request->action());
        $mobile_url = config('site.mobile_domain');
        if ($this->request->isMobile()) {
            $this->redirect($mobile_url . '/m/' . $controller . '/' . $action);
        }
        $this->uid = session('xwx_user_id');
        $this->prefix = Env::get('database.prefix');
        $this->redis_prefix = Env::get('cache.prefix');
        $this->end_point = config('seo.book_end_point');
        $tpl_root = './template/' . config('site.tpl') . '/pc/';
        $this->tpl = $tpl_root . $controller . '/' . $action . '.html';
        $this->links = cache('friendshipLink');
        $this->url = config('site.domain');
        if (!$this->links) {
            $this->links = FriendshipLink::select();
            cache('friendshipLink', $this->links, null, 'redis');
        }
        View::assign([
            'url' => $this->url,
            'site_name' => config('site.site_name'),
            'mobile_url' => $mobile_url,
            'book_ctrl' => BOOKCTRL,
            'chapter_ctrl' => CHAPTERCTRL,
            'booklist_act' => BOOKLISTACT,
            'search_ctrl' => SEARCHCTRL,
            'rank_ctrl' => RANKCTRL,
            'update_act' => UPDATEACT,
            'author_ctrl' => AUTHORCTRL,
            'end_point' => config('seo.book_end_point'),
            'xwx_user_id' => session('xwx_user_id'),
            'xwx_user' => session('xwx_user'),
            'xwx_nick_name' => session('xwx_nick_name'),
            'xwx_user_mobile' => session('xwx_user_mobile'),
            'links' => $this->links
        ]);
    }
}